version: '3'

services:
  spring-config-server:
    image: spring-config-server:1.0-SNAPSHOT
    environment:
        SPRING_PROFILES_ACTIVE: 'repos-conf'
    ports:
        - "7777:7777"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
        - "5672:5672"

  spring-cb-server:
    image: spring-cb-server:1.0-SNAPSHOT
    ports:
        - "8090:8090"

  spring-cb-delay-client:
    depends_on:
      - rabbitmq
    image: spring-cb-delay-client:1.0-SNAPSHOT
    environment:
        SPRING_RABBITMQ_HOST: rabbitmq
        CONFIG_SERVER_URL: 'http://192.168.99.100:7777'
        #SERVER_URL: 'http://192.168.99.100:8090'
        #CLIENT_SERVER_READ_TIMEOUT_MILLIS: 5000
        #HYSTRIX_TIMEOUT_ENABLED: 'false'
        #HYSTRIX_TIMEOUT_MILLIS: 1000
        #HYSTRIX_REQUEST_VOLUME_THRESHOLD: 2
        #HYSTRIX_SLEEP_WINDOW_MILLIS: 10000
        #HYSTRIX_ERROR_THRESHOLD_PERCENTAGE: 50
    ports:
        - "8091:8091"

  spring-cb-error-client:
    depends_on:
      - rabbitmq
    image: spring-cb-error-client:1.0-SNAPSHOT
    environment:
        SPRING_RABBITMQ_HOST: rabbitmq
        CONFIG_SERVER_URL: 'http://192.168.99.100:7777'
        #SERVER_URL: 'http://192.168.99.100:8090'
        #CLIENT_SERVER_READ_TIMEOUT_MILLIS: 5000
        #HYSTRIX_TIMEOUT_ENABLED: 'false'
        #HYSTRIX_TIMEOUT_MILLIS: 1000
        #HYSTRIX_REQUEST_VOLUME_THRESHOLD: 10
        #HYSTRIX_SLEEP_WINDOW_MILLIS: 5000
        #HYSTRIX_ERROR_THRESHOLD_PERCENTAGE: 50
    ports:
        - "8092:8092"

  spring-cb-turbine:
    depends_on:
      - rabbitmq
    image: spring-cb-turbine:1.0-SNAPSHOT
    environment:
        SPRING_RABBITMQ_HOST: rabbitmq
    ports:
        - "8989:8989"

  spring-cb-dashboard:
    image: spring-cb-dashboard:1.0-SNAPSHOT
    ports:
        - "9080:9080"
